[package]
name = "ctgen"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "^0"
tokio = { version = "^1.28", features = ["full"] }
log = "^0"
env_logger = "^0"
anyhow = "^1.0"
dotenvy = "^0.15"
clap = { version = "^4", features = ["derive"] }
dirs = "^5"
toml = "^0"
indexmap = { version = "^2", features = ["serde"] }
serde_json = "^1.0"
serde = { version = "^1", features = ["derive"] }
handlebars = { version = "^4", features = ["dir_source"] }
handlebars-inflector = "^0.1.0"
handlebars-concat = "^0.1.0"

database-reflection = { path = "../database-reflection" }
