[profile]
name = "test"
env-file = ".env"
env-var = "DB_CONNECTION"
dsn = ""
target-dir = "target"
templates-dir = "assets/templates"
scripts-dir = "assets/scripts"
prompts = [ "dummy", "columns", "order", "submodules" ]
targets = [ "test", "dbdoc" ]

[prompt.dummy]
prompt = "Do you like pizza?"
options = { 1 = "Yes", 0 = "No" }

[prompt.columns]
prompt = "Select grid columns:"
options = "{{concat table/columns}}"
multiple = true

[prompt.order]
condition = "{{#each table/columns}}{{#if (eq name \"position\")}}1{{/if}}{{/each}}"
prompt = "Add order page?"
options = { 1 = "Yes", 0 = "No" }

[prompt.submodules]
condition = "{{#if (gt (len constraints_foreign) 0)}}1{{/if}}"
prompt = "Select submodules to add?"
options = "{{#each constraints_foreign}}{{key_pairs.[0].local.table}}.{{key_pairs.[0].local.name}}{{#unless @last}},{{/unless}}{{/each}}"
multiple = true

[target.test]
template = "test"
target = "render/{{table/name}}.md"
#formatter = "tail -n 10 {{target}}"

[target.dbdoc]
template = "dbdoc"
target = "render/dbdoc.md"
formatter = "tail -n 10 {{target}}"