[profile]
name = "test"
env-file = ".env"
env-var = "DB_CONNECTION"
dsn = ""
target-dir = "."
templates-dir = "assets/templates"
scripts-dir = "assets/scripts"
prompts = [ "dummy" ]
targets = [ "test" ]

[prompt.dummy]
prompt = "Would you like to proceed?"
options = { 1 = "Yes", 0 = "No" }

[target.test]
template = "test"
target = "target/render/{{table/name}}.md"
