[profile]
name = "test"
env-file = ".env"
env-var = "DB_CONNECTION"
dsn = ""
target-dir = "."
templates-dir = "assets/templates"
scripts-dir = "assets/scripts"
prompts = [ "columns", "order", "submodules" ]
targets = [ "rust", "react" ]

[prompt.columns]
prompt = "Select grid columns:"
options = "{{concat table/columns}}"
multiple = true

[prompt.order]
condition = "{{#each table/columns}}{{#if (eq name \"position\")}}1{{/if}}{{/each}}"
prompt = "Add order page?"
options = { 1 = "Yes", 0 = "No" }

[prompt.submodules]
condition = "{{#if (gt (len constraints_foreign) 0)}}1{{/if}}"
prompt = "Select submodules to add?"
options = "{{#each constraints_foreign}}{{key_pairs.[0].local.table}}.{{key_pairs.[0].local.name}}{{#unless @last}},{{/unless}}{{/each}}"
multiple = true

[target.rust]
template = "backend/rust_actix_graphql"
target = "src/backend/{{table/name}}.rs"
formatter = "cargo fmt"

[target.react]
template = "frontend/react_admin"
target = "backend/src/routes/{{inflect table/name to_pascal_case=true}}.rs"
formatter = "npx prettify"