[profile]
name = "test"
env_file = ".env"
env_var = "DB_CONNECTION"
database_str = ""
target_dir = "."
templates_dir = "assets/templates"
scripts_dir = "assets/scripts"
prompts = [ "dummy" ]
targets = [ "test" ]

[prompt.dummy]
prompt = "Would you like to proceed?"
options = { 1 = "Yes", 0 = "No" }

[target.test]
template = "test"
target = "target/render/{{table/name}}.md"
